# from guess import *

import sys

class game(object):
    outputList = []
    outputList2 = []
    def __init__(self, game, word, status, guess, letter, score):
       """
        The constructor used for the initialization of the object
       :param game: This is the game id of the game
       :param word: This is the random word generated by the stringDatabase class
       :param status: Returns whether user was able to guess the word or he quits
       :param guess: Number of times the wrong guesses registered by the user
       :param letter: Number of times the wrong letters registered by the user
       :param score: Prints the score of the game
       """
       self.game = game;
       self.word = word;
       self.status = status;
       self.guess = guess;
       self.letter = letter;
       self.score = score;
       print()

